# Generated by Django 5.1.3 on 2024-11-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='USER_ID', primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(db_column='FULL_NAME', max_length=255)),
                ('username', models.CharField(db_column='USERNAME', max_length=255, unique=True)),
                ('address', models.CharField(db_column='ADDRESS', max_length=255)),
                ('phone', models.CharField(db_column='PHONE', max_length=10)),
                ('email', models.EmailField(db_column='EMAIL', max_length=255, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
                ('date_of_birth', models.DateField(db_column='DOB')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
