# Generated by Django 5.1.3 on 2024-11-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
    ]
