# Generated by Django 5.1.3 on 2024-11-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='IS_SUPERUSER', default=True),
        ),
    ]
